"""
Email Builder - Generate HTML digest emails with embedded vote links.
"""

import html
from datetime import datetime, timezone


class EmailBuilder:
    """Build HTML digest emails."""

    def __init__(self, language: str = "zh", repo_owner: str = "", repo_name: str = ""):
        self.lang = language
        self.repo_owner = repo_owner
        self.repo_name = repo_name

    def _vote_url(self, paper_id: str, vote: str, keywords: list[str]) -> str:
        """Generate a one-click vote URL via the vote landing page."""
        import urllib.parse
        kw_str = ",".join(keywords[:5])
        repo = f"{self.repo_owner}/{self.repo_name}"
        # Vote page hosted on GitHub Pages
        base = f"https://{self.repo_owner}.github.io/{self.repo_name}/setup/vote.html"
        params = urllib.parse.urlencode({
            "repo": repo,
            "paper_id": paper_id,
            "vote": vote,
            "keywords": kw_str,
        })
        return f"{base}?{params}"

    def build(self, papers: list[dict]) -> tuple[str, str]:
        today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        if self.lang == "zh":
            subject = f"学术论文日报 - {today} ({len(papers)} 篇新论文)"
        else:
            subject = f"Paper Digest - {today} ({len(papers)} new papers)"
        return subject, self._render_html(papers, today)

    def _render_html(self, papers: list[dict], date_str: str) -> str:
        zh = self.lang == "zh"
        T = {
            "title": "学术论文日报" if zh else "Paper Digest",
            "subtitle": f"{date_str} · 共 {len(papers)} 篇相关论文" if zh else f"{date_str} · {len(papers)} relevant papers",
            "score": "相关度" if zh else "Relevance",
            "kw": "匹配关键词" if zh else "Matched keywords",
            "ai": "AI 分析" if zh else "AI Analysis",
            "vote": "为这篇论文打分：" if zh else "Rate this paper:",
            "bad": "👎 不感兴趣" if zh else "👎 Not interested",
            "ok": "👌 一般" if zh else "👌 Neutral",
            "good": "🔥 非常相关" if zh else "🔥 Very relevant",
            "footer": "由 Paper Digest Bot 自动生成" if zh else "Auto-generated by Paper Digest Bot",
        }

        cards = ""
        for paper in papers:
            title = html.escape(paper.get("title", "Untitled"))
            url = html.escape(paper.get("url", "#"))
            authors_list = paper.get("authors", [])
            authors = html.escape(", ".join(authors_list[:5]))
            if len(authors_list) > 5:
                authors += " et al."
            source = html.escape(paper.get("source", ""))
            score = paper.get("relevance_score", 0)
            matched_kw = paper.get("matched_keywords", [])
            ai_text = html.escape(paper.get("ai_summary", ""))
            pid = html.escape(paper.get("id", ""))

            badges = " ".join(
                f'<span style="display:inline-block;background:#e8f0fe;color:#1a56db;'
                f'padding:2px 8px;border-radius:12px;font-size:12px;margin:2px;">'
                f'{html.escape(k)}</span>'
                for k in matched_kw
            )
            sc = "#16a34a" if score >= 3 else "#ca8a04" if score >= 1.5 else "#6b7280"
            v_bad = html.escape(self._vote_url(pid, "not_interested", matched_kw))
            v_ok = html.escape(self._vote_url(pid, "neutral", matched_kw))
            v_good = html.escape(self._vote_url(pid, "very_relevant", matched_kw))

            cards += f"""
<div style="background:#fff;border:1px solid #e5e7eb;border-radius:12px;padding:20px;margin-bottom:16px;">
  <div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:8px;">
    <span style="background:{sc};color:#fff;padding:2px 10px;border-radius:10px;font-size:12px;font-weight:600;">{T['score']}: {score:.1f}</span>
    <span style="color:#9ca3af;font-size:12px;">{source}</span>
  </div>
  <h2 style="margin:8px 0;font-size:16px;line-height:1.4;">
    <a href="{url}" style="color:#111827;text-decoration:none;" target="_blank">{title}</a>
  </h2>
  <p style="color:#6b7280;font-size:13px;margin:4px 0 12px;">{authors}</p>
  <div style="margin-bottom:12px;">{badges}</div>
  <div style="background:#f9fafb;border-left:3px solid #6366f1;padding:12px 16px;border-radius:0 8px 8px 0;margin-bottom:16px;">
    <p style="color:#6366f1;font-size:11px;font-weight:600;margin:0 0 4px;text-transform:uppercase;">{T['ai']}</p>
    <p style="color:#374151;font-size:14px;line-height:1.6;margin:0;">{ai_text}</p>
  </div>
  <div style="border-top:1px solid #f3f4f6;padding-top:12px;">
    <p style="color:#9ca3af;font-size:12px;margin:0 0 8px;">{T['vote']}</p>
    <div>
      <a href="{v_bad}" style="display:inline-block;padding:6px 16px;margin-right:8px;background:#fee2e2;color:#dc2626;border-radius:8px;font-size:13px;text-decoration:none;">{T['bad']}</a>
      <a href="{v_ok}" style="display:inline-block;padding:6px 16px;margin-right:8px;background:#f3f4f6;color:#6b7280;border-radius:8px;font-size:13px;text-decoration:none;">{T['ok']}</a>
      <a href="{v_good}" style="display:inline-block;padding:6px 16px;background:#dcfce7;color:#16a34a;border-radius:8px;font-size:13px;text-decoration:none;">{T['good']}</a>
    </div>
  </div>
</div>"""

        owner = html.escape(self.repo_owner)
        repo = html.escape(self.repo_name)
        return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f3f4f6;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
<div style="max-width:640px;margin:0 auto;padding:24px 16px;">
  <div style="text-align:center;margin-bottom:24px;">
    <h1 style="font-size:24px;color:#111827;margin:0 0 4px;">{T['title']}</h1>
    <p style="color:#9ca3af;font-size:14px;margin:0;">{T['subtitle']}</p>
  </div>
  {cards}
  <div style="text-align:center;padding:24px 0;color:#9ca3af;font-size:12px;">
    <p>{T['footer']}</p>
    <p><a href="https://github.com/{owner}/{repo}" style="color:#6366f1;">GitHub Repo</a></p>
  </div>
</div></body></html>"""
